### ISSUE TITLE
Cannot find template: "index.html"

### ISSUE THREAD

**Issue by jtpio** [vidartf/phoila#3]
While trying to look in `$PREFIX/phoila/share/jupyter/phoila/static`.

Steps:

1. `git clone`
2. `python -m pip install .`
3. `phoila`

**Comment by jtpio** [comment]
ok it seems like there should be at least one lab extension installed (to create the bundle)

**Comment by vidartf** [comment]
Or just do `phoila build` :)

**Comment by vidartf** [comment]
Did a quick thing to the README: https://github.com/vidartf/phoila/commit/380933d6a2dd324af0640ab54cd3e9b8aee3945a

**Comment by jtpio** [comment]
yeah that works too :)

**Comment by jtpio** [comment]
Thanks @vidartf
